### PR TITLE
Closes #166

### LINKED ISSUE #166: Make sure we don't allow competing continuous migrations
Currently, don't think there is a catch to make sure we haven't specified continuous migration between the same source/dest demes that have overlapping time intervals.

E.g., this should result in an error:
```YAML
migrations:
- symmetric:
  - demes: A, B
    rate: 0.01
  - demes: A, B
    rate: 0.02
```

### PR DESCRIPTION
**Pull request by apragsdale**
Checks non-overlap of migration start/end times if they involve the same source/dest. Am I missing any cases here?

### CODE REVIEW

**Comment by apragsdale** [comment]
Ah, yes this seems to be failing from the hypothesis draws. @grahamgower is that an easy change to writing those tests that you had in mind? Or requires some major rewriting..?

**Comment by grahamgower** [comment]
At the moment, `graphs()` adds all demes in a loop, then draws all migrations/pulses in another loop. It could be changed to draw mutations/pulses in the deme-adding loop, just between the currently added deme and the existing demes. It would then be easier to limit migrations to be non-time-overlapping for each deme pair. E.g. see how times are drawn in the `epochs_lists()` function above it, to draw a set of unique times, sort them, and then use them as non-overlapping time intervals.

**Comment by apragsdale** [comment]
Ok, trying something here to avoid adding overlapping migrations to a random graph in the tests...

**Comment by apragsdale** [comment]
Hey @grahamgower ... not sure what this error here means in build-deploy-docs: "Error: Input required and not supplied: token". Do we need to update something in setting up github actions?

**Comment by grahamgower** [comment]
Ah, sorry about the docs action failure. I disabled that for forks, because github suggested there's a security issue with it (Ben Jeffery told me he'll come up with a way of doing this differently). So for now, pull requests from forks will get permission errors from the docs github action. If it gets too annoying, I'll temporarily delete the action. Or you can push a branch to the `popsim-consortium/demes-python` repo, and open a pull request from there (which will have the right permissions). This all applies to the demes-spec repo too, btw.

**Review by grahamgower — APPROVED** [review]
LGTM @apragsdale.

**Review by jeromekelleher — APPROVED** [review]
LGTM also

**Comment by apragsdale** [comment]
Is this ok to merge and just ignore that error for now, then?

**Comment by jeromekelleher** [comment]
Fine by me

**Pull request merged**
