### PR TITLE
Handle invalid proportions

### PR DESCRIPTION
**Pull request by molpopgen**
See #576

### CODE REVIEW

**Comment by grahamgower** [comment]
It looks like the runner is trying to execute:
```
pip install --upgrade pip pip install -r requirements.txt
```
Which kinda makes sense in light of the error message:
```
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
```
That part of the .yml files hasn't changed, but maybe there's a newline issue here that is newly problematic? Mixed dos/unix newlines?

**Comment by molpopgen** [comment]
@grahamgower -- I think some of the issue has to do w/the CI being quite out of date.  I saw similar errors in the demes-spec PRs before the CI there got updated.

**Comment by grahamgower** [comment]
The docs build seems to be working here. It's also working for me offline, with Python 3.11. Maybe just rebase this and apply fixes for the proportions? We can do the update to Python 3.12 separately.

**Review by grahamgower — APPROVED** [review]
LGTM.

**Comment by grahamgower** [comment]
Oooh, codecov isn't broken, it really is just overloaded!

**Pull request merged**
