### PR TITLE
Ms converted models have diploid population sizes.

### LINKED ISSUE #458: from_ms docs say N0 measures "haploid" individuals
In the docs I wrote that `N_0 * x` gives deme sizes in with units of haploid individuals.
https://popsim-consortium.github.io/demes-docs/latest/api.html#demes.from_ms

But msdoc.pdf says `N_0` measures diploid individuals. Help!

### PR DESCRIPTION
**Pull request by grahamgower**
Fixes #458.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I get this wrong about 50% of the time, so going to ping @molpopgen here!

**Comment by molpopgen** [comment]
Dammit.  I'll have to rewind my brain to 2013 and get back to you... :)

**Comment by molpopgen** [comment]
Looking at the linked issue, @grahamgower is stating that an imported `ms` model gives results ~identical in distribution to a diploid sim using `msprime.sim_ancestry`.  That's basically the check that I would do.  But if you've already done it, then I think we are good?  I can peek at those tests if anyone thinks that would help?

**Comment by molpopgen** [comment]
> 

okay, will do.

**Comment by molpopgen** [comment]
I found the verification.py very difficult to follow.  I could not find and hand-written ms command lines?  What am I missing?

So, I wrote this modification of the above.  The output for `from_demes = True` agrees with `from_demes=False`, at least as far as the mean is concerned.  Does this satisfy the question?

```py
import msprime
import numpy as np
import demes

# n haploid samples
def total_time(n, nreps=1000, from_demes=False, Ne=1.0):
    # assert n // 2 == n / 2
    ttl_time_from_msp = []
    tmrca_from_msp = []
    if from_demes is True:
        demography = msprime.Demography.from_demes(demes.from_ms("", N0=Ne))
        population_size = None
    else:
        demography = None
        population_size = Ne

    for ts in msprime.sim_ancestry(
        samples=[msprime.SampleSet(num_samples=n, ploidy=1)],
        demography=demography,
        population_size=population_size,
        ploidy=2,
        num_replicates=nreps,
    ):
        assert len([i for i in ts.samples()]) == n
        for t in ts.trees():
            ttl_time_from_msp.append(t.total_branch_length)
            assert t.num_roots == 1
            for root in t.roots:
                tmrca_from_msp.append(ts.node(root).time)
    # This is the expected total time in units of 4Ne
    # generations
    # References: e.g., Hudson 1990
    ettot = np.array([1 / i for i in range(1, n)]).sum()

    # E(TMRCA) from theory, also generations/4Ne.
    etmrca = 1 - 1 / n

    # The msprime times are in units of Ne generations,
    # so we have a factor of 4 to deal with:
    print(f"n = {n}, from_demes = {from_demes}, Ne = {Ne}")
    print(np.array(ttl_time_from_msp).mean(), 4.0 * Ne * ettot)
    print(np.array(tmrca_from_msp).mean(), 4.0 * Ne * etmrca)


# n haploid samples
def total_time_bottleneck(n, nreps=1000, from_demes=False, Ne=1.0):
    # assert n // 2 == n / 2
    ttl_time_from_msp = []
    tmrca_from_msp = []
    ms_bneck_time = 0.25
    ms_bneck_end_time = 0.35
    if from_demes is True:
        demography = msprime.Demography.from_demes(
            demes.from_ms(f"-eN {ms_bneck_time} 0.1 -eN {ms_bneck_end_time} 1", N0=Ne)
        )
        population_size = None
    else:
        yaml = f"""
        time_units: generations
        demes:
         - name: A
           epochs:
            - start_size: {Ne}
              end_time: {4*Ne*ms_bneck_end_time}
            - start_size: {0.1*Ne}
              end_time: {4*Ne*ms_bneck_time}
            - start_size: {Ne}
        """
        print(yaml)
        demography = msprime.Demography.from_demes(demes.loads(yaml))
        population_size = None

    for ts in msprime.sim_ancestry(
        samples=[msprime.SampleSet(num_samples=n, ploidy=1)],
        demography=demography,
        population_size=population_size,
        ploidy=2,
        num_replicates=nreps,
    ):
        assert len([i for i in ts.samples()]) == n
        for t in ts.trees():
            ttl_time_from_msp.append(t.total_branch_length)
            assert t.num_roots == 1
            for root in t.roots:
                tmrca_from_msp.append(ts.node(root).time)

    # The msprime times are in units of Ne generations,
    # so we have a factor of 4 to deal with:
    print(f"n = {n}, from_demes = {from_demes}, Ne = {Ne}")
    print(np.array(ttl_time_from_msp).mean())
    print(np.array(tmrca_from_msp).mean())


# for Ne in [1, 100, 10000]:
#     for n in [10, 50, 100]:
#         total_time(n, Ne=Ne, nreps=10000)
#         total_time(n, from_demes=True, Ne=Ne, nreps=10000)
for Ne in [1, 100, 10000]:
    for n in [10, 50, 100]:
        total_time_bottleneck(n, Ne=Ne, nreps=10000)
        total_time_bottleneck(n, from_demes=True, Ne=Ne, nreps=10000)
```

**Comment by grahamgower** [comment]
I'm convinced. Thanks @molpopgen!

Sorry the verification.py script is hard to read---I guess it got a bit convoluted when I refactored things to parallelise it, and it wasn't worth making the code easier to read. The goal there was to verify that `to_demes()` got basic model features correct, in particular the migration and pulse directions. There are also unit tests in `tests/test_ms.py` that check `from_ms(to_ms(...))` in a range of scenarios. So unless you think there are improvements that can be made to the docs beyond this PR, then I think this can be merged?

**Comment by molpopgen** [comment]
I think this can be safely merged at this point.

**Pull request merged**
